version: 2

builds:
  - id: api
    main: ./cmd/api
    binary: api
    ldflags:
      - -s -w -X github.com/patrickmoriarty/api-cli/internal/app.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

brews:
  - name: api
    description: "api is a scriptable API client"
    homepage: "https://github.com/patrickmoriarty/api-cli"
    repository:
      owner: patrickmoriarty
      name: homebrew-tap
      branch: main
    directory: Formula
