version: 2

builds:
  - id: api
    main: ./cmd/api
    binary: api
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w -X github.com/patrickjm/api-cli/internal/app.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc

brews:
  - name: api
    description: "api is a scriptable API client"
    homepage: "https://github.com/patrickjm/api-cli"
    repository:
      owner: patrickjm
      name: homebrew-tap
      branch: main
    directory: Formula
